# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
FROM alpine:3.22.1
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	BASE_REL=0.9.20251111 \
	BASE_SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v0.9.20251111.tar.gz \
	TZ=Asia/Jerusalem \
	USER=client
COPY LICENSES/* /licenses/

# hadolint ignore=DL4006
RUN \
	apk add --no-cache --update \
		curl~=8.14 \
		iproute2~=6.15 \
		netcat-openbsd~=1.229 \
		tzdata~=2025 \
	&& rm -rf /var/cache/apk/* \
	&& adduser -D -u 1001 "$USER" "$USER" \
	&& cp /usr/share/zoneinfo/"$TZ" /etc/localtime \
	&& printf %s "$TZ" > /etc/timezone \
	&& curl --location --silent "$BASE_SRC" | \
		tar \
			--directory /usr/local/bin \
			--extract \
			--gzip \
			--strip-components=2 \
			shellbase-"$BASE_REL"/lib/base.sh
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	client/client .
CMD ["./client"]
