// Settings:
:toc: macro
:!toc-title:

// URLs:
:img-build: https://github.com/rdavid/pulse/actions/workflows/build.yml/badge.svg
:img-hoc: https://hitsofcode.com/github/rdavid/pulse?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/pulse?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/pulse?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test-lnx: https://github.com/rdavid/pulse/actions/workflows/test-lnx.yml/badge.svg
:img-test-mac: https://github.com/rdavid/pulse/actions/workflows/test-mac.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-build: https://github.com/rdavid/pulse/actions/workflows/build.yml
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/pulse?branch=master
:url-license: https://github.com/rdavid/pulse/blob/master/LICENSES/0BSD.txt
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/pulse/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellbase: https://github.com/rdavid/shellbase
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test-lnx: https://github.com/rdavid/pulse/actions/workflows/test-lnx.yml
:url-test-mac: https://github.com/rdavid/pulse/actions/workflows/test-mac.yml
:url-typos: https://github.com/crate-ci/typos
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Pulse

[subs=attributes+]
++++
<div align="right">
<a href="{url-build}"><img src="{img-build}" alt="build"></a>
<a href="{url-test-lnx}"><img src="{img-test-lnx}" alt="test lnx"></a>
<a href="{url-test-mac}"><img src="{img-test-mac}" alt="test mac"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-releases}"><img src="{img-releases}" alt="release"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/pulse" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

Pulse is a client-server network communication project.
A containerized client collects monitoring data and reports it to a
containerized server.
Both are POSIX-compliant shell
(Portable Operating System Interface for uniX) scripts built on the Unix
shell framework {url-shellbase}[`shellbase`].

== Objectives

Both the client and the server run on the `alpine` base image.
Every five seconds the client sends the following data to the server:

* Host uptime
* Host network interface names and IP addresses

The server stores the received data in a database.
After every five status updates, the server sends a kill signal to restart
the client service.

== Build and Start

To build and start the containers with Podman Compose:

[,sh]
----
# Starts VM.
podman machine start

# Builds both images and starts containers.
podman-compose up --build

# Stops and removes containers.
podman-compose down

# Stops VM.
podman machine stop
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].
It also parses each script with `dash` and `mksh` to reject syntax the
project's target shells do not accept.

== License

`pulse` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>pulse by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/pulse" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/pulse/releases" target="_blank" rel="noopener">Releases</a>
    <a href="https://github.com/rdavid/pulse/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
