// Settings:
:toc: macro
:!toc-title:

// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/pulse?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/pulse?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-test-lnx: https://github.com/rdavid/pulse/actions/workflows/test-lnx.yml/badge.svg
:img-test-mac: https://github.com/rdavid/pulse/actions/workflows/test-mac.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-cv: http://cv.rabkin.co.il
:url-goredo: http://www.goredo.cypherpunks.su/Install.html
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/pulse?branch=master
:url-license: https://github.com/rdavid/pulse/blob/master/LICENSES/0BSD.txt
:url-redo: http://cr.yp.to/redo.html
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellbase: https://github.com/rdavid/shellbase
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test-lnx: https://github.com/rdavid/pulse/actions/workflows/test-lnx.yml
:url-test-mac: https://github.com/rdavid/pulse/actions/workflows/test-mac.yml
:url-typos: https://github.com/crate-ci/typos
:url-yamllint: https://github.com/adrienverge/yamllint

= Pulse

image:{img-test-lnx}[test lnx,link={url-test-lnx}]
image:{img-test-mac}[test mac,link={url-test-mac}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

Pulse is a client-server network communication project.
The project is implemented using POSIX-compliant Shell
`Portable Operating System Interface for uniX`, and utilizes the Unix shell
framework {url-shellbase}[`shellbase`].

== Build

To build and start the containers with Podman Compose:

[,sh]
----
# Starts VM.
podman machine start

# Builds both images and start containers.
podman-compose up --build

# Stops and removes containers.
podman-compose down

# Stops VM.
podman machine stop
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-yamllint}[`yamllint`].

== License

`pulse` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
