# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: build
'on':
  pull_request:
    paths: &paths
      - client/**
      - server/**
  push:
    branches: [master]
    paths: *paths
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    timeout-minutes: 15
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: redhat-actions/buildah-build@v2.13
        with:
          containerfiles: ./client/Containerfile
          image: pulse-client
          tags: latest
      - uses: redhat-actions/buildah-build@v2.13
        with:
          containerfiles: ./server/Containerfile
          image: pulse-server
          tags: latest
