# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: publish
'on':
  push:
    tags:
      - v*
permissions:
  contents: read
  packages: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
env:
  CLIENT: ${{ github.repository }}-client
  REGISTRY: ghcr.io
  SERVER: ${{ github.repository }}-server
jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v4.2.0
      - uses: docker/setup-buildx-action@v4.2.0
      - uses: docker/login-action@v4.3.0
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - uses: docker/metadata-action@v6.2.0
        id: meta-client
        with:
          images: ${{ env.REGISTRY }}/${{ env.CLIENT }}
          labels: |
            maintainer=David Rabkin
            org.opencontainers.image.description=Client -> Server
            org.opencontainers.image.licenses=0BSD
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.title=Pulse Client
            org.opencontainers.image.vendor=David Rabkin
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},priority=901
      - uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: client/Containerfile
          labels: ${{ steps.meta-client.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.meta-client.outputs.tags }}
      - uses: docker/metadata-action@v6.2.0
        id: meta-server
        with:
          images: ${{ env.REGISTRY }}/${{ env.SERVER }}
          labels: |
            maintainer=David Rabkin
            org.opencontainers.image.description=Server -> Client
            org.opencontainers.image.licenses=0BSD
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.title=Pulse Server
            org.opencontainers.image.vendor=David Rabkin
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},priority=901
      - uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: server/Containerfile
          labels: ${{ steps.meta-server.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
