# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: test-lnx
'on': [pull_request, push]
jobs:
  test-lnx:
    timeout-minutes: 15
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo apt update
          sudo apt install --yes podman python3-pip
          pip3 install --user podman-compose
          mkdir dat
          chmod a+w dat
          podman-compose \
            --file podman-compose-test.yml \
            up --build --detach
          sleep 5
          podman-compose \
            --file podman-compose-test.yml \
            down
